development:
  adapter: postgresql
  encoding: unicode
  database: qrp_development
  pool: 5
  username: neilmarion
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: qrp_test
  pool: 5
  username: neilmarion
  password: root
